name: Download File
on:
  schedule:
    - cron:  "0 14 * * *"
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - uses: actions/checkout@v3
      - uses: wow-actions/download-upload@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          url: https://info.gesundheitsministerium.gv.at/data/timeline-testungen-bundeslaender.csv
          filename: ${{ steps.date.outputs.date }}.csv
          dir: timeline-testungen-bundeslaender
          commit_message: 'downloaded on ${{ github.event.repository.updated_at}}'
      - uses: wow-actions/download-upload@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          url: https://info.gesundheitsministerium.gv.at/data/COVID19_vaccination_doses_timeline_v202206.csv
          filename: ${{ steps.date.outputs.date }}.csv
          dir: COVID19_vaccination_doses_timeline_v202206
          commit_message: 'downloaded on ${{ github.event.repository.updated_at}}'
